version: '3.9'

services:
  egonsystem:
    build: .
    container_name: streamlit-egonsystem
    ports:
      - "9990:8501"
    volumes:
      - ./datalake:/app/datalake
    environment:
      - PYTHONPATH=/app
    env_file:
      - .env
